import type { BusinessCardProps } from "@/components/BusinessCard";

export interface SeedBusiness extends BusinessCardProps {
  id: string;
  address: string;
  phone: string;
  website: string;
  yelpRating: number;
  yelpReviewCount: number;
  qualificationScore: number;
  qualified: boolean;
  yearsInBusiness: number;
}

export const SEED_BUSINESSES: SeedBusiness[] = [
  {
    id: "biz-001",
    slug: "cool-air-hvac-heights",
    name: "Cool Air HVAC Solutions",
    category: "HVAC",
    neighborhood: "Houston Heights",
    address: "1420 Yale St, Houston, TX 77008",
    phone: "(713) 555-0101",
    website: "https://coolair-hvac.example.com",
    googleRating: 4.9,
    googleReviewCount: 312,
    yelpRating: 4.8,
    yelpReviewCount: 187,
    qualificationScore: 97.2,
    qualified: true,
    yearsInBusiness: 12,
    tier: "premium",
    year: 2026,
  },
  {
    id: "biz-002",
    slug: "montrose-dental-care",
    name: "Montrose Dental Care",
    category: "Dentist",
    neighborhood: "Montrose",
    address: "3801 Westheimer Rd, Houston, TX 77027",
    phone: "(713) 555-0202",
    website: "https://montrose-dental.example.com",
    googleRating: 4.8,
    googleReviewCount: 428,
    yelpRating: 4.7,
    yelpReviewCount: 203,
    qualificationScore: 95.8,
    qualified: true,
    yearsInBusiness: 8,
    tier: "pro",
    year: 2026,
  },
  {
    id: "biz-003",
    slug: "midtown-bites-restaurant",
    name: "Midtown Bites",
    category: "Restaurant",
    neighborhood: "Midtown",
    address: "2503 Fannin St, Houston, TX 77002",
    phone: "(713) 555-0303",
    website: "https://midtownbites.example.com",
    googleRating: 4.7,
    googleReviewCount: 891,
    yelpRating: 4.6,
    yelpReviewCount: 634,
    qualificationScore: 94.1,
    qualified: true,
    yearsInBusiness: 5,
    tier: "premium",
    year: 2026,
  },
  {
    id: "biz-004",
    slug: "galleria-auto-repair",
    name: "Galleria Auto Repair",
    category: "Auto Repair",
    neighborhood: "Galleria",
    address: "5555 Richmond Ave, Houston, TX 77056",
    phone: "(713) 555-0404",
    website: "https://galleria-auto.example.com",
    googleRating: 4.8,
    googleReviewCount: 156,
    yelpRating: 4.7,
    yelpReviewCount: 98,
    qualificationScore: 91.5,
    qualified: true,
    yearsInBusiness: 15,
    tier: "pro",
    year: 2026,
  },
  {
    id: "biz-005",
    slug: "river-oaks-legal-group",
    name: "River Oaks Legal Group",
    category: "Law Firm",
    neighborhood: "River Oaks",
    address: "2727 Allen Pkwy, Houston, TX 77019",
    phone: "(713) 555-0505",
    website: "https://ro-legal.example.com",
    googleRating: 4.9,
    googleReviewCount: 74,
    yelpRating: 4.8,
    yelpReviewCount: 41,
    qualificationScore: 89.3,
    qualified: true,
    yearsInBusiness: 22,
    tier: "basic",
    year: 2026,
  },
  {
    id: "biz-006",
    slug: "eado-fitness-studio",
    name: "EaDo Fitness Studio",
    category: "Gym",
    neighborhood: "East Downtown",
    address: "2602 Canal St, Houston, TX 77003",
    phone: "(713) 555-0606",
    website: "https://eado-fitness.example.com",
    googleRating: 4.6,
    googleReviewCount: 203,
    yelpRating: 4.5,
    yelpReviewCount: 119,
    qualificationScore: 87.4,
    qualified: true,
    yearsInBusiness: 4,
    tier: "pro",
    year: 2026,
  },
  {
    id: "biz-007",
    slug: "the-woodlands-plumbing",
    name: "The Woodlands Plumbing Co.",
    category: "Plumbing",
    neighborhood: "The Woodlands",
    address: "2219 Sawdust Rd, The Woodlands, TX 77380",
    phone: "(281) 555-0707",
    website: "https://twp-plumbing.example.com",
    googleRating: 4.5,
    googleReviewCount: 88,
    yelpRating: 4.4,
    yelpReviewCount: 52,
    qualificationScore: 82.1,
    qualified: true,
    yearsInBusiness: 9,
    tier: "basic",
    year: 2026,
  },
  {
    id: "biz-008",
    slug: "sugarland-vet-clinic",
    name: "Sugar Land Veterinary Clinic",
    category: "Veterinarian",
    neighborhood: "Sugar Land",
    address: "77 Sugar Creek Center Blvd, Sugar Land, TX 77478",
    phone: "(281) 555-0808",
    website: "https://slvet.example.com",
    googleRating: 4.7,
    googleReviewCount: 340,
    yelpRating: 4.6,
    yelpReviewCount: 198,
    qualificationScore: 93.0,
    qualified: true,
    yearsInBusiness: 11,
    tier: "premium",
    year: 2026,
  },
  // Not-yet-qualified businesses (score too low or doesn't meet cutoff)
  {
    id: "biz-009",
    slug: "pearland-tax-prep",
    name: "Pearland Tax Prep",
    category: "Accounting",
    neighborhood: "Pearland",
    address: "2800 Business Center Dr, Pearland, TX 77584",
    phone: "(281) 555-0909",
    website: "https://pearland-tax.example.com",
    googleRating: 3.9,
    googleReviewCount: 32,
    yelpRating: 3.8,
    yelpReviewCount: 14,
    qualificationScore: 0.0,
    qualified: false,
    yearsInBusiness: 2,
    year: 2026,
  },
  {
    id: "biz-010",
    slug: "katy-roofing-solutions",
    name: "Katy Roofing Solutions",
    category: "Roofing",
    neighborhood: "Katy",
    address: "1550 Katy Fort Bend Rd, Katy, TX 77494",
    phone: "(281) 555-1010",
    website: "https://katy-roofing.example.com",
    googleRating: 4.1,
    googleReviewCount: 45,
    yelpRating: 4.0,
    yelpReviewCount: 27,
    qualificationScore: 0.0,
    qualified: false,
    yearsInBusiness: 3,
    year: 2026,
  },
];

export const QUALIFIED_BUSINESSES = SEED_BUSINESSES.filter((b) => b.qualified);
